import Head from 'next/head'
import Videos from '../components/Videos'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Videos />
    </div>
  )
}
